name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      
   # - name: Build the Docker image
   #   run: docker build . --file Dockerfile --tag palopalepalo/paloblog:${{ github.sha }}
    -   name: Set up QEMU
        uses: docker/setup-qemu-action@v1
    
    -   name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
    -   name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
    -   name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile 
          tags: palopalepalo/paloblog:${{ github.sha }}
    
    -   name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
    - name: Run Trivy vulnerability scanner      
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'palopalepalo/paloblog:${{ github.sha }}'
        format: 'table'
        exit-code: '0'
        severity: 'MEDIUM,HIGH,CRITICAL'

  deploy:
    
    needs: [build]
    runs-on: ubuntu-18.04
    
    steps: 
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Go agains boiss"
          cd ~/re-cloud
          docker rm -f jekyll-ci
          docker rmi $(docker images -aq)
          docker run --name jekyll-ci -d -p 3000:4000 --volume="$PWD:/srv/jekyll" --env JEKYLL_UID=1001 --env JEKYLL_GID=1001 -it palopalepalo/paloblog:${{ github.sha }} jekyll serve


 
